version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
      - "9000:9000"
    volumes:
      - wp_vol:/var/www/html
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - maria_vol:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/WordPress
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    ports:
      - "9000:9000"
volumes:
  maria_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/Desktop/inception/project/srcs/DB
  wp_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/Desktop/inception/project/srcs/WordPress
networks:
  inception:
    driver: bridge